spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: example
    password: example

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false